[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@ds/=lib/multicall/lib/ds-test/src/",
    "@std/=lib/multicall/lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "multicall/=lib/multicall/src/",
    "superfluid-protocol-monorepo/=lib/superfluid-protocol-monorepo/packages/solidity-semantic-money/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
